name: foodpundit
description: "Healthy eating simplified"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  line_icons: ^2.0.3
  camera: ^0.11.0+2
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  # Firebase
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2
  firebase_core: ^3.8.0
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3
  # google_sign_in: ^6.1.6
  sign_in_with_apple: ^6.1.3
  cloud_firestore: ^5.5.0
  # State Management
  provider: ^6.1.1
  url_launcher: ^6.2.4
  # Animations
  connectivity_plus: ^5.0.2
  flutter_svg: ^2.0.9
  intl: ^0.20.1
  http: ^1.1.0
  http_parser: ^4.0.2
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  yaml: ^3.1.2
  yaml_edit: ^2.1.1
  mockito: ^5.0.16

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/images/
    - assets/images/onboarding/
    - assets/icons/
    - assets/icons/nutriscore/
    - assets/icons/novagroup/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
